// <auto-generated />
using System;
using MVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.Migrations
{
    [DbContext(typeof(MVCContext))]
    [Migration("20240720102947_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<int>("MinDegree")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = 100,
                            DepartmentId = 1,
                            Hours = 100,
                            MinDegree = 55,
                            Name = ".NET"
                        },
                        new
                        {
                            Id = 2,
                            Degree = 90,
                            DepartmentId = 1,
                            Hours = 80,
                            MinDegree = 50,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 3,
                            Degree = 95,
                            DepartmentId = 1,
                            Hours = 90,
                            MinDegree = 53,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 4,
                            Degree = 85,
                            DepartmentId = 2,
                            Hours = 70,
                            MinDegree = 50,
                            Name = "Human Resources Management"
                        },
                        new
                        {
                            Id = 5,
                            Degree = 88,
                            DepartmentId = 2,
                            Hours = 75,
                            MinDegree = 52,
                            Name = "Recruitment Strategies"
                        },
                        new
                        {
                            Id = 6,
                            Degree = 90,
                            DepartmentId = 2,
                            Hours = 80,
                            MinDegree = 55,
                            Name = "Employee Relations"
                        },
                        new
                        {
                            Id = 7,
                            Degree = 92,
                            DepartmentId = 3,
                            Hours = 85,
                            MinDegree = 54,
                            Name = "Financial Accounting"
                        },
                        new
                        {
                            Id = 8,
                            Degree = 95,
                            DepartmentId = 3,
                            Hours = 90,
                            MinDegree = 55,
                            Name = "Corporate Finance"
                        },
                        new
                        {
                            Id = 9,
                            Degree = 90,
                            DepartmentId = 3,
                            Hours = 80,
                            MinDegree = 52,
                            Name = "Investment Management"
                        },
                        new
                        {
                            Id = 10,
                            Degree = 93,
                            DepartmentId = 4,
                            Hours = 85,
                            MinDegree = 55,
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = 11,
                            Degree = 88,
                            DepartmentId = 4,
                            Hours = 75,
                            MinDegree = 50,
                            Name = "Marketing Research"
                        },
                        new
                        {
                            Id = 12,
                            Degree = 91,
                            DepartmentId = 4,
                            Hours = 80,
                            MinDegree = 53,
                            Name = "Consumer Behavior"
                        },
                        new
                        {
                            Id = 13,
                            Degree = 95,
                            DepartmentId = 5,
                            Hours = 90,
                            MinDegree = 55,
                            Name = "Networking"
                        },
                        new
                        {
                            Id = 14,
                            Degree = 92,
                            DepartmentId = 5,
                            Hours = 85,
                            MinDegree = 54,
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = 15,
                            Degree = 90,
                            DepartmentId = 5,
                            Hours = 80,
                            MinDegree = 52,
                            Name = "Database Management"
                        });
                });

            modelBuilder.Entity("MVC.Models.CourseResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int?>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CoursesResult");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Degree = 88,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Degree = 75,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            Degree = 90,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 1,
                            Degree = 85,
                            TraineeId = 4
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 1,
                            Degree = 92,
                            TraineeId = 5
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 2,
                            Degree = 80,
                            TraineeId = 6
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 2,
                            Degree = 87,
                            TraineeId = 7
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 2,
                            Degree = 79,
                            TraineeId = 8
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 2,
                            Degree = 84,
                            TraineeId = 9
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 2,
                            Degree = 91,
                            TraineeId = 10
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 3,
                            Degree = 83,
                            TraineeId = 11
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 3,
                            Degree = 88,
                            TraineeId = 12
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 3,
                            Degree = 82,
                            TraineeId = 13
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 3,
                            Degree = 86,
                            TraineeId = 14
                        },
                        new
                        {
                            Id = 15,
                            CourseId = 3,
                            Degree = 90,
                            TraineeId = 15
                        },
                        new
                        {
                            Id = 16,
                            CourseId = 4,
                            Degree = 88,
                            TraineeId = 16
                        },
                        new
                        {
                            Id = 17,
                            CourseId = 4,
                            Degree = 75,
                            TraineeId = 17
                        },
                        new
                        {
                            Id = 18,
                            CourseId = 4,
                            Degree = 90,
                            TraineeId = 18
                        },
                        new
                        {
                            Id = 19,
                            CourseId = 4,
                            Degree = 85,
                            TraineeId = 19
                        },
                        new
                        {
                            Id = 20,
                            CourseId = 4,
                            Degree = 92,
                            TraineeId = 20
                        },
                        new
                        {
                            Id = 21,
                            CourseId = 5,
                            Degree = 80,
                            TraineeId = 21
                        },
                        new
                        {
                            Id = 22,
                            CourseId = 5,
                            Degree = 87,
                            TraineeId = 22
                        },
                        new
                        {
                            Id = 23,
                            CourseId = 5,
                            Degree = 79,
                            TraineeId = 23
                        },
                        new
                        {
                            Id = 24,
                            CourseId = 5,
                            Degree = 84,
                            TraineeId = 24
                        },
                        new
                        {
                            Id = 25,
                            CourseId = 5,
                            Degree = 91,
                            TraineeId = 25
                        },
                        new
                        {
                            Id = 26,
                            CourseId = 6,
                            Degree = 83,
                            TraineeId = 26
                        },
                        new
                        {
                            Id = 27,
                            CourseId = 6,
                            Degree = 88,
                            TraineeId = 27
                        },
                        new
                        {
                            Id = 28,
                            CourseId = 6,
                            Degree = 82,
                            TraineeId = 28
                        },
                        new
                        {
                            Id = 29,
                            CourseId = 6,
                            Degree = 86,
                            TraineeId = 29
                        },
                        new
                        {
                            Id = 30,
                            CourseId = 6,
                            Degree = 90,
                            TraineeId = 30
                        },
                        new
                        {
                            Id = 31,
                            CourseId = 7,
                            Degree = 88,
                            TraineeId = 31
                        },
                        new
                        {
                            Id = 32,
                            CourseId = 7,
                            Degree = 75,
                            TraineeId = 32
                        },
                        new
                        {
                            Id = 33,
                            CourseId = 7,
                            Degree = 90,
                            TraineeId = 33
                        },
                        new
                        {
                            Id = 34,
                            CourseId = 7,
                            Degree = 85,
                            TraineeId = 34
                        },
                        new
                        {
                            Id = 35,
                            CourseId = 7,
                            Degree = 92,
                            TraineeId = 35
                        },
                        new
                        {
                            Id = 36,
                            CourseId = 8,
                            Degree = 80,
                            TraineeId = 36
                        },
                        new
                        {
                            Id = 37,
                            CourseId = 8,
                            Degree = 87,
                            TraineeId = 37
                        },
                        new
                        {
                            Id = 38,
                            CourseId = 8,
                            Degree = 79,
                            TraineeId = 38
                        },
                        new
                        {
                            Id = 39,
                            CourseId = 8,
                            Degree = 84,
                            TraineeId = 39
                        },
                        new
                        {
                            Id = 40,
                            CourseId = 8,
                            Degree = 91,
                            TraineeId = 40
                        },
                        new
                        {
                            Id = 41,
                            CourseId = 9,
                            Degree = 83,
                            TraineeId = 41
                        },
                        new
                        {
                            Id = 42,
                            CourseId = 9,
                            Degree = 88,
                            TraineeId = 42
                        },
                        new
                        {
                            Id = 43,
                            CourseId = 9,
                            Degree = 82,
                            TraineeId = 43
                        },
                        new
                        {
                            Id = 44,
                            CourseId = 9,
                            Degree = 86,
                            TraineeId = 44
                        },
                        new
                        {
                            Id = 45,
                            CourseId = 9,
                            Degree = 90,
                            TraineeId = 45
                        },
                        new
                        {
                            Id = 46,
                            CourseId = 10,
                            Degree = 88,
                            TraineeId = 46
                        },
                        new
                        {
                            Id = 47,
                            CourseId = 10,
                            Degree = 75,
                            TraineeId = 47
                        },
                        new
                        {
                            Id = 48,
                            CourseId = 10,
                            Degree = 90,
                            TraineeId = 48
                        },
                        new
                        {
                            Id = 49,
                            CourseId = 10,
                            Degree = 85,
                            TraineeId = 49
                        },
                        new
                        {
                            Id = 50,
                            CourseId = 10,
                            Degree = 92,
                            TraineeId = 50
                        },
                        new
                        {
                            Id = 51,
                            CourseId = 11,
                            Degree = 80,
                            TraineeId = 51
                        },
                        new
                        {
                            Id = 52,
                            CourseId = 11,
                            Degree = 87,
                            TraineeId = 52
                        },
                        new
                        {
                            Id = 53,
                            CourseId = 11,
                            Degree = 79,
                            TraineeId = 53
                        },
                        new
                        {
                            Id = 54,
                            CourseId = 11,
                            Degree = 84,
                            TraineeId = 54
                        },
                        new
                        {
                            Id = 55,
                            CourseId = 11,
                            Degree = 91,
                            TraineeId = 55
                        },
                        new
                        {
                            Id = 56,
                            CourseId = 12,
                            Degree = 83,
                            TraineeId = 56
                        },
                        new
                        {
                            Id = 57,
                            CourseId = 12,
                            Degree = 88,
                            TraineeId = 57
                        },
                        new
                        {
                            Id = 58,
                            CourseId = 12,
                            Degree = 82,
                            TraineeId = 58
                        },
                        new
                        {
                            Id = 59,
                            CourseId = 12,
                            Degree = 86,
                            TraineeId = 59
                        },
                        new
                        {
                            Id = 60,
                            CourseId = 12,
                            Degree = 90,
                            TraineeId = 60
                        },
                        new
                        {
                            Id = 61,
                            CourseId = 13,
                            Degree = 88,
                            TraineeId = 61
                        },
                        new
                        {
                            Id = 62,
                            CourseId = 13,
                            Degree = 75,
                            TraineeId = 62
                        },
                        new
                        {
                            Id = 63,
                            CourseId = 13,
                            Degree = 90,
                            TraineeId = 63
                        },
                        new
                        {
                            Id = 64,
                            CourseId = 13,
                            Degree = 85,
                            TraineeId = 64
                        },
                        new
                        {
                            Id = 65,
                            CourseId = 13,
                            Degree = 92,
                            TraineeId = 65
                        },
                        new
                        {
                            Id = 66,
                            CourseId = 14,
                            Degree = 80,
                            TraineeId = 66
                        },
                        new
                        {
                            Id = 67,
                            CourseId = 14,
                            Degree = 87,
                            TraineeId = 67
                        },
                        new
                        {
                            Id = 68,
                            CourseId = 14,
                            Degree = 79,
                            TraineeId = 68
                        },
                        new
                        {
                            Id = 69,
                            CourseId = 14,
                            Degree = 84,
                            TraineeId = 69
                        },
                        new
                        {
                            Id = 70,
                            CourseId = 14,
                            Degree = 91,
                            TraineeId = 70
                        },
                        new
                        {
                            Id = 71,
                            CourseId = 15,
                            Degree = 83,
                            TraineeId = 71
                        },
                        new
                        {
                            Id = 72,
                            CourseId = 15,
                            Degree = 88,
                            TraineeId = 72
                        },
                        new
                        {
                            Id = 73,
                            CourseId = 15,
                            Degree = 82,
                            TraineeId = 73
                        },
                        new
                        {
                            Id = 74,
                            CourseId = 15,
                            Degree = 86,
                            TraineeId = 74
                        },
                        new
                        {
                            Id = 75,
                            CourseId = 15,
                            Degree = 90,
                            TraineeId = 75
                        });
                });

            modelBuilder.Entity("MVC.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manager = "Mohamed",
                            Name = "SD"
                        },
                        new
                        {
                            Id = 2,
                            Manager = "Sara",
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Manager = "John",
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            Manager = "Linda",
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Manager = "Alex",
                            Name = "IT"
                        });
                });

            modelBuilder.Entity("MVC.Models.Instructore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructore");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo",
                            CourseId = 1,
                            DepartmentId = 1,
                            Image = "avatar.png",
                            Name = "Mohamed",
                            Salary = 2500
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza",
                            CourseId = 1,
                            DepartmentId = 1,
                            Image = "avatar.png",
                            Name = "Ahmed",
                            Salary = 2600
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alexandria",
                            CourseId = 2,
                            DepartmentId = 1,
                            Image = "avatar.png",
                            Name = "Amina",
                            Salary = 2700
                        },
                        new
                        {
                            Id = 4,
                            Address = "Luxor",
                            CourseId = 2,
                            DepartmentId = 1,
                            Image = "avatar.png",
                            Name = "Omar",
                            Salary = 2800
                        },
                        new
                        {
                            Id = 5,
                            Address = "Aswan",
                            CourseId = 3,
                            DepartmentId = 1,
                            Image = "avatar.png",
                            Name = "Sara",
                            Salary = 2900
                        },
                        new
                        {
                            Id = 6,
                            Address = "Suez",
                            CourseId = 3,
                            DepartmentId = 1,
                            Image = "avatar.png",
                            Name = "Mona",
                            Salary = 3000
                        },
                        new
                        {
                            Id = 7,
                            Address = "Cairo",
                            CourseId = 4,
                            DepartmentId = 2,
                            Image = "avatar.png",
                            Name = "Hassan",
                            Salary = 3100
                        },
                        new
                        {
                            Id = 8,
                            Address = "Giza",
                            CourseId = 4,
                            DepartmentId = 2,
                            Image = "avatar.png",
                            Name = "Reem",
                            Salary = 3200
                        },
                        new
                        {
                            Id = 9,
                            Address = "Alexandria",
                            CourseId = 5,
                            DepartmentId = 2,
                            Image = "avatar.png",
                            Name = "Nour",
                            Salary = 3300
                        },
                        new
                        {
                            Id = 10,
                            Address = "Luxor",
                            CourseId = 5,
                            DepartmentId = 2,
                            Image = "avatar.png",
                            Name = "Layla",
                            Salary = 3400
                        },
                        new
                        {
                            Id = 11,
                            Address = "Aswan",
                            CourseId = 6,
                            DepartmentId = 2,
                            Image = "avatar.png",
                            Name = "Khaled",
                            Salary = 3500
                        },
                        new
                        {
                            Id = 12,
                            Address = "Suez",
                            CourseId = 6,
                            DepartmentId = 2,
                            Image = "avatar.png",
                            Name = "Fatma",
                            Salary = 3600
                        },
                        new
                        {
                            Id = 13,
                            Address = "Cairo",
                            CourseId = 7,
                            DepartmentId = 3,
                            Image = "avatar.png",
                            Name = "Ali",
                            Salary = 3700
                        },
                        new
                        {
                            Id = 14,
                            Address = "Giza",
                            CourseId = 7,
                            DepartmentId = 3,
                            Image = "avatar.png",
                            Name = "Zainab",
                            Salary = 3800
                        },
                        new
                        {
                            Id = 15,
                            Address = "Alexandria",
                            CourseId = 8,
                            DepartmentId = 3,
                            Image = "avatar.png",
                            Name = "Tamer",
                            Salary = 3900
                        },
                        new
                        {
                            Id = 16,
                            Address = "Luxor",
                            CourseId = 8,
                            DepartmentId = 3,
                            Image = "avatar.png",
                            Name = "Hoda",
                            Salary = 4000
                        },
                        new
                        {
                            Id = 17,
                            Address = "Aswan",
                            CourseId = 9,
                            DepartmentId = 3,
                            Image = "avatar.png",
                            Name = "Mahmoud",
                            Salary = 4100
                        },
                        new
                        {
                            Id = 18,
                            Address = "Suez",
                            CourseId = 9,
                            DepartmentId = 3,
                            Image = "avatar.png",
                            Name = "Laila",
                            Salary = 4200
                        },
                        new
                        {
                            Id = 19,
                            Address = "Cairo",
                            CourseId = 10,
                            DepartmentId = 4,
                            Image = "avatar.png",
                            Name = "Samir",
                            Salary = 4300
                        },
                        new
                        {
                            Id = 20,
                            Address = "Giza",
                            CourseId = 10,
                            DepartmentId = 4,
                            Image = "avatar.png",
                            Name = "Heba",
                            Salary = 4400
                        },
                        new
                        {
                            Id = 21,
                            Address = "Alexandria",
                            CourseId = 11,
                            DepartmentId = 4,
                            Image = "avatar.png",
                            Name = "Youssef",
                            Salary = 4500
                        },
                        new
                        {
                            Id = 22,
                            Address = "Luxor",
                            CourseId = 11,
                            DepartmentId = 4,
                            Image = "avatar.png",
                            Name = "Dina",
                            Salary = 4600
                        },
                        new
                        {
                            Id = 23,
                            Address = "Aswan",
                            CourseId = 12,
                            DepartmentId = 4,
                            Image = "avatar.png",
                            Name = "Rania",
                            Salary = 4700
                        },
                        new
                        {
                            Id = 24,
                            Address = "Suez",
                            CourseId = 12,
                            DepartmentId = 4,
                            Image = "avatar.png",
                            Name = "Hussein",
                            Salary = 4800
                        },
                        new
                        {
                            Id = 25,
                            Address = "Cairo",
                            CourseId = 13,
                            DepartmentId = 5,
                            Image = "avatar.png",
                            Name = "Fady",
                            Salary = 4900
                        },
                        new
                        {
                            Id = 26,
                            Address = "Giza",
                            CourseId = 13,
                            DepartmentId = 5,
                            Image = "avatar.png",
                            Name = "Mariam",
                            Salary = 5000
                        },
                        new
                        {
                            Id = 27,
                            Address = "Alexandria",
                            CourseId = 14,
                            DepartmentId = 5,
                            Image = "avatar.png",
                            Name = "Ola",
                            Salary = 5100
                        },
                        new
                        {
                            Id = 28,
                            Address = "Luxor",
                            CourseId = 14,
                            DepartmentId = 5,
                            Image = "avatar.png",
                            Name = "Karim",
                            Salary = 5200
                        },
                        new
                        {
                            Id = 29,
                            Address = "Aswan",
                            CourseId = 15,
                            DepartmentId = 5,
                            Image = "avatar.png",
                            Name = "Farah",
                            Salary = 5300
                        },
                        new
                        {
                            Id = 30,
                            Address = "Suez",
                            CourseId = 15,
                            DepartmentId = 5,
                            Image = "avatar.png",
                            Name = "Basma",
                            Salary = 5400
                        });
                });

            modelBuilder.Entity("MVC.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo",
                            DepartmentId = 1,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Mohamed"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza",
                            DepartmentId = 1,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Ahmed"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alexandria",
                            DepartmentId = 1,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Sara"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Luxor",
                            DepartmentId = 1,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Omar"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Aswan",
                            DepartmentId = 1,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Amina"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Suez",
                            DepartmentId = 1,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Hassan"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Cairo",
                            DepartmentId = 1,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Reem"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Giza",
                            DepartmentId = 1,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Nour"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Alexandria",
                            DepartmentId = 1,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Ali"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Luxor",
                            DepartmentId = 1,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Zainab"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Aswan",
                            DepartmentId = 1,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Tamer"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Suez",
                            DepartmentId = 1,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Laila"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Cairo",
                            DepartmentId = 1,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Mahmoud"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Giza",
                            DepartmentId = 1,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Samir"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Alexandria",
                            DepartmentId = 1,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Heba"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Cairo",
                            DepartmentId = 2,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Youssef"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Giza",
                            DepartmentId = 2,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Dina"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Alexandria",
                            DepartmentId = 2,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Rania"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Luxor",
                            DepartmentId = 2,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Hussein"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Aswan",
                            DepartmentId = 2,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Fady"
                        },
                        new
                        {
                            Id = 21,
                            Address = "Suez",
                            DepartmentId = 2,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Mariam"
                        },
                        new
                        {
                            Id = 22,
                            Address = "Cairo",
                            DepartmentId = 2,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Ola"
                        },
                        new
                        {
                            Id = 23,
                            Address = "Giza",
                            DepartmentId = 2,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Karim"
                        },
                        new
                        {
                            Id = 24,
                            Address = "Alexandria",
                            DepartmentId = 2,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Farah"
                        },
                        new
                        {
                            Id = 25,
                            Address = "Luxor",
                            DepartmentId = 2,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Basma"
                        },
                        new
                        {
                            Id = 26,
                            Address = "Aswan",
                            DepartmentId = 2,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Fahd"
                        },
                        new
                        {
                            Id = 27,
                            Address = "Suez",
                            DepartmentId = 2,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Nadine"
                        },
                        new
                        {
                            Id = 28,
                            Address = "Cairo",
                            DepartmentId = 2,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Hala"
                        },
                        new
                        {
                            Id = 29,
                            Address = "Giza",
                            DepartmentId = 2,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Salma"
                        },
                        new
                        {
                            Id = 30,
                            Address = "Alexandria",
                            DepartmentId = 2,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Hadi"
                        },
                        new
                        {
                            Id = 31,
                            Address = "Cairo",
                            DepartmentId = 3,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Lina"
                        },
                        new
                        {
                            Id = 32,
                            Address = "Giza",
                            DepartmentId = 3,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Marwa"
                        },
                        new
                        {
                            Id = 33,
                            Address = "Alexandria",
                            DepartmentId = 3,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Hani"
                        },
                        new
                        {
                            Id = 34,
                            Address = "Luxor",
                            DepartmentId = 3,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Kareem"
                        },
                        new
                        {
                            Id = 35,
                            Address = "Aswan",
                            DepartmentId = 3,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Shereen"
                        },
                        new
                        {
                            Id = 36,
                            Address = "Suez",
                            DepartmentId = 3,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Ziad"
                        },
                        new
                        {
                            Id = 37,
                            Address = "Cairo",
                            DepartmentId = 3,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Nada"
                        },
                        new
                        {
                            Id = 38,
                            Address = "Giza",
                            DepartmentId = 3,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Tarek"
                        },
                        new
                        {
                            Id = 39,
                            Address = "Alexandria",
                            DepartmentId = 3,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Mai"
                        },
                        new
                        {
                            Id = 40,
                            Address = "Luxor",
                            DepartmentId = 3,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Rami"
                        },
                        new
                        {
                            Id = 41,
                            Address = "Aswan",
                            DepartmentId = 3,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Hadeer"
                        },
                        new
                        {
                            Id = 42,
                            Address = "Suez",
                            DepartmentId = 3,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Fadi"
                        },
                        new
                        {
                            Id = 43,
                            Address = "Cairo",
                            DepartmentId = 3,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Sherif"
                        },
                        new
                        {
                            Id = 44,
                            Address = "Giza",
                            DepartmentId = 3,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Lamis"
                        },
                        new
                        {
                            Id = 45,
                            Address = "Alexandria",
                            DepartmentId = 3,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Amr"
                        },
                        new
                        {
                            Id = 46,
                            Address = "Cairo",
                            DepartmentId = 4,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Yasmin"
                        },
                        new
                        {
                            Id = 47,
                            Address = "Giza",
                            DepartmentId = 4,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Ayman"
                        },
                        new
                        {
                            Id = 48,
                            Address = "Alexandria",
                            DepartmentId = 4,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Nahla"
                        },
                        new
                        {
                            Id = 49,
                            Address = "Luxor",
                            DepartmentId = 4,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Dalia"
                        },
                        new
                        {
                            Id = 50,
                            Address = "Aswan",
                            DepartmentId = 4,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Sami"
                        },
                        new
                        {
                            Id = 51,
                            Address = "Suez",
                            DepartmentId = 4,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Maha"
                        },
                        new
                        {
                            Id = 52,
                            Address = "Cairo",
                            DepartmentId = 4,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Lila"
                        },
                        new
                        {
                            Id = 53,
                            Address = "Giza",
                            DepartmentId = 4,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Nader"
                        },
                        new
                        {
                            Id = 54,
                            Address = "Alexandria",
                            DepartmentId = 4,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Rana"
                        },
                        new
                        {
                            Id = 55,
                            Address = "Luxor",
                            DepartmentId = 4,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Adel"
                        },
                        new
                        {
                            Id = 56,
                            Address = "Aswan",
                            DepartmentId = 4,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Farida"
                        },
                        new
                        {
                            Id = 57,
                            Address = "Suez",
                            DepartmentId = 4,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Tala"
                        },
                        new
                        {
                            Id = 58,
                            Address = "Cairo",
                            DepartmentId = 4,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Lamis"
                        },
                        new
                        {
                            Id = 59,
                            Address = "Giza",
                            DepartmentId = 4,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Jamal"
                        },
                        new
                        {
                            Id = 60,
                            Address = "Alexandria",
                            DepartmentId = 4,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Malak"
                        },
                        new
                        {
                            Id = 61,
                            Address = "Cairo",
                            DepartmentId = 5,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Rasha"
                        },
                        new
                        {
                            Id = 62,
                            Address = "Giza",
                            DepartmentId = 5,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Salem"
                        },
                        new
                        {
                            Id = 63,
                            Address = "Alexandria",
                            DepartmentId = 5,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Ibrahim"
                        },
                        new
                        {
                            Id = 64,
                            Address = "Luxor",
                            DepartmentId = 5,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Zaki"
                        },
                        new
                        {
                            Id = 65,
                            Address = "Aswan",
                            DepartmentId = 5,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Ghada"
                        },
                        new
                        {
                            Id = 66,
                            Address = "Suez",
                            DepartmentId = 5,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Ismail"
                        },
                        new
                        {
                            Id = 67,
                            Address = "Cairo",
                            DepartmentId = 5,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Nadia"
                        },
                        new
                        {
                            Id = 68,
                            Address = "Giza",
                            DepartmentId = 5,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Samir"
                        },
                        new
                        {
                            Id = 69,
                            Address = "Alexandria",
                            DepartmentId = 5,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Hala"
                        },
                        new
                        {
                            Id = 70,
                            Address = "Luxor",
                            DepartmentId = 5,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Kamal"
                        },
                        new
                        {
                            Id = 71,
                            Address = "Aswan",
                            DepartmentId = 5,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Yara"
                        },
                        new
                        {
                            Id = 72,
                            Address = "Suez",
                            DepartmentId = 5,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Omar"
                        },
                        new
                        {
                            Id = 73,
                            Address = "Cairo",
                            DepartmentId = 5,
                            Grade = "Grade 1",
                            Image = "avatar.png",
                            Name = "Bassem"
                        },
                        new
                        {
                            Id = 74,
                            Address = "Giza",
                            DepartmentId = 5,
                            Grade = "Grade 2",
                            Image = "avatar.png",
                            Name = "Nourhan"
                        },
                        new
                        {
                            Id = 75,
                            Address = "Alexandria",
                            DepartmentId = 5,
                            Grade = "Grade 3",
                            Image = "avatar.png",
                            Name = "Tarek"
                        });
                });

            modelBuilder.Entity("MVC.Models.Course", b =>
                {
                    b.HasOne("MVC.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVC.Models.Instructore", b =>
                {
                    b.HasOne("MVC.Models.Course", "Course")
                        .WithMany("Instructores")
                        .HasForeignKey("CourseId");

                    b.HasOne("MVC.Models.Department", "Department")
                        .WithMany("Instructores")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVC.Models.Trainee", b =>
                {
                    b.HasOne("MVC.Models.Course", "Course")
                        .WithMany("Trainees")
                        .HasForeignKey("CourseId");

                    b.HasOne("MVC.Models.Department", "Department")
                        .WithMany("Trainees")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVC.Models.Course", b =>
                {
                    b.Navigation("Instructores");

                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("MVC.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructores");

                    b.Navigation("Trainees");
                });
#pragma warning restore 612, 618
        }
    }
}
